import { Eventdetails } from  './event.model';
import { Profiledetails } from './profile.model';
import { Injectable } from '@angular/core';

@Injectable()
export class MainService {

  private d;
  private y;
  private i;
  private currentGallery : string[] = [];
  private events = new Map([['2018', [ new Eventdetails('Summer Camp 2018','23-3-2018','punaloor', '../../assets/e1.jpg'), new Eventdetails('Winter Camp','23-3-2018','punaloor', '../../assets/e2.jpg') 
  ]], ['2017', [ new Eventdetails('Summer Camp 2017','23-3-2018','punaloor', '../../assets/e1.jpg'), new Eventdetails('Winter Camp','23-3-2018','punaloor', '../../assets/e2.jpg') 
]] ]); 
  
  
  private gallery = new Map([
    ['2018', ['../../assets/s1-imo.png', '../../assets/s2-imo.png']],
    ['2017', ['../../assets/s2-imo.png']]
  ]);

  

  private profiles = [
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename',null, "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old."),
    new Profiledetails('samplename','../../assets/s4-imo.png', "As a direct descendent of  Okinawan Karate's Shito-Ryu style, Shukokai has inherited the characteristics of both  Naha-te and Shuri-te styles.  It was MABUNI  Kenwa  who merged the techniques and principles of  both styles which  he had himself learned from his teachers HIGASHIONNA Kanryu  and  ITOSHU Ankoto, into  his own Karate style: Shito-Ryu , which Tani Chojiro will later turn into Shukokai. As a result, Shukokai combines the Naha-te circular breathing techniques  and the Shuri-te quick linear movements. This is most apparent in some  of the many Shukokai.'s Katas , such as  Sanchin, Tensho,  Suparunpei which come from  the Naha-te tradition,  or   Annanko, Matsukaze, and Bassai-Dai, derived from the Shuri-te tradition. Shukokai is  noticeable for its relatively high number of katas . This is a direct result of MABUNI Kenwa's experience with both the Naha-te and Shuri -te styles as well as his encounter with other teacher's styles. Mabuni  was known  as \"the foremost expert on kata\" all over Japan. Although Shukokai shares many of  the punches, kicks, and blocks with other popular styles of Karate, the way it executes them  sets Shukokai apart. TANI chojiro, who created Shukokai from MABUNI's Shito Ryu's inheritance spent his lifespan enriching his style continuously refining each technique to the highest degree, mainly re-defining the basics which had been practiced for centuries. Shukokai  makes the study of the body's mechanics his primary focus and the delivery of the greatest impact with the least amount of effort as the end result.  Another characteristic is that each technique must be combat effective.Both TANI Chojiro  and his successor MASUYAMA  Takeshi,   believe  that a technique, as powerful as it may be, is  useless if it cannot  be delivered under combat situations. Remember, Karate was originally a means of self-defense, not a sport. Their philosophy  is thus, that the outcome of a confrontation should be decided in a single technique, \"one hit one kill\", as per the way of the samurais of old.")
  ]

  constructor() { }

  getCurrentEvents()
  {
    return this.events.values().next();
  }

  getCurrentGallery()
  {
    return this.gallery.values().next();
  }

  getCurrentGalleryYear()
  {
    return this.gallery.keys().next();
  }

  getProfiles()
  {
    return this.profiles;
  }

  getEvents()
  {
    console.log(this.events);
    return this.events;
  }

  getGallery()
  {
    return this.gallery;
  }
}
